changelog:
  categories:
    - title: ":memo: Changelog"
      labels:
        - "*"
      exclude:
        labels:
          - dependencies
          - release
    - title: ":toolbox: Dependencies"
      labels:
        - dependencies