site_name: Proteus Wiki
site_url: https://kaktushose.github.io/proteus/

theme:
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.top
    - navigation.footer
    - toc.integrate
    - toc.follow
    - search.share
    - search.suggest
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
  name: material
  icon:
    repo: fontawesome/brands/github
    logo: material/book-open-page-variant
    admonition:
      link: octicons/link-16
  palette:
    scheme: slate
    primary: green
    accent: blue
  font:
    text: Roboto
    code: Roboto Mono
  custom_dir: overrides

repo_name: Proteus
repo_url: https://github.com/kaktushose/proteus

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/kaktushose
  version:
    default: wiki
    provider: mike

copyright: Copyright &copy; 2025 Kaktushose

plugins:
  - search
#  - open-in-new-tab

markdown_extensions:
  - pymdownx.blocks.caption
  - admonition
  - pymdownx.details
  - pymdownx.highlight
  - footnotes
  - tables
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - Home: index.md
  - Types: types.md
  - Mappers: mappers.md
  - Conversion: conversion.md
  - Javadocs: https://kaktushose.github.io/proteus/javadocs/0/