name: Java CI

on:
  push:
    branches: [ main, feature/*, ci/speed-up-gradle ]
  pull_request:
    branches: [ main, feature/* ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '23'
          cache: gradle
      - name: Build and test with Gradle
        run: gradle test --no-daemon
