name: Java CI

on:
  push:
    branches: [ main, feature/*, ci/speed-up-gradle ]
  pull_request:
    branches: [ main, feature/* ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: wrapper
      - name: Build and test with Gradle
        run: gradle test
